Initalizing the bundle for the builds for Openshift operator
redhat-openshift-builds/operator pull request #11
Opened 2024-06-26 08:58 UTC by ayushsatyam146

2024-06-26 13:29 UTC, avinal commented
Please add pull request description.

2024-06-27 08:21 UTC, sayan-biswas requested changes

2024-06-27 08:21 UTC, sayan-biswas commented on config/manifests/bases/operator.clusterserviceversion.yaml
> +  namespace: placeholder
the namespace should be `openshift-build`

2024-06-27 08:21 UTC, sayan-biswas commented on config/manifests/bases/operator.clusterserviceversion.yaml
> +  name: operator.v0.0.0
semantic version is required.

2024-06-27 08:21 UTC, sayan-biswas commented on config/manifests/bases/operator.clusterserviceversion.yaml
> +  customresourcedefinitions:
we'll need the `shipwrightbuilds.operator.shipwright.io` CRD also

2024-06-27 08:21 UTC, sayan-biswas commented on config/manifests/bases/operator.clusterserviceversion.yaml
> +  installModes:
@avinal This refers to you story.

2024-06-27 08:21 UTC, sayan-biswas commented on config/manifests/bases/operator.clusterserviceversion.yaml
> +  version: 0.0.0
semantic version required

2024-06-27 08:21 UTC, sayan-biswas commented on bundle/tests/scorecard/config.yaml
> +apiVersion: scorecard.operatorframework.io/v1alpha3
Not sure whether we need scorecard deployment.

2024-07-01 06:50 UTC, sayan-biswas approved these changes

2024-07-01 06:50 UTC, merged