fix: Boostrap OpenShiftBuild Object
redhat-openshift-builds/operator pull request #34
Opened 2024-07-15 19:39 UTC by adambkaplan

- Move bootstrap logic outside of `SetupWithManager`, run before controllers start instead.
- Change singleton OpenShiftBuild name to `cluster`.
- Update tests to remove OpenShiftBuild finalizers prior to deletion.

2024-07-16 01:29 UTC, sayan-biswas requested changes

2024-07-16 01:29 UTC, sayan-biswas commented on internal/controller/openshiftbuild_controller.go
> +	result, err := r.CreateOrUpdate(ctx, bootstrapOpenShiftBuild)
So we can just do `r.Client.Get()` instead of `CreateOrUpdate` in the `Reconcile` method.
https://glorious-tribble-54gr7j9q7rfpgrj.github.dev/

2024-07-16 18:38 UTC, adambkaplan commented on internal/controller/openshiftbuild_controller.go
> +	result, err := r.CreateOrUpdate(ctx, bootstrapOpenShiftBuild)
I decided to take a different approach to minimize impact on the current code. I'm continuing to use `CreateOrUpdate`, but passing it a `client.Client` object instead. The main `Reconcile` loop passes in the client that the controller-runtime manager initializes. The `Bootstrap...` method accepts any client, which is initialized more or less as you described in `main.go`.

2024-07-17 00:26 UTC, sayan-biswas approved these changes

2024-07-17 00:26 UTC, merged

2024-07-17 01:17 UTC, sayan-biswas commented on internal/controller/openshiftbuild_controller.go
> +	result, err := r.CreateOrUpdate(ctx, bootstrapOpenShiftBuild)
While working on this, I discovered that controller-runtime added the `APIReader` interface for this purpose, which bypasses the cache. But yes, for now we minimise the impact on the current code.