feat: Pod and container security context
redhat-openshift-builds/operator pull request #47
Opened 2024-07-22 10:16 UTC by sayan-biswas

Changes:
- Use `manifestival` transformer to remove `runAsUser` and `runAsGroup` from yamls.

2024-07-22 15:58 UTC, adambkaplan requested changes

2024-07-22 15:58 UTC, adambkaplan commented on internal/common/transformer.go
> +func SecurityContext(object *unstructured.Unstructured) error {
Style nit - be specific when naming things and writing godoc:

```suggestion
// RemoveRunAsUserRunAsGroup is a Manifestival transformer function that removes runAsUser and runAsGroup from a Deployment container's security context
func SecurityContext(object *unstructured.Unstructured) error {
```

2024-07-22 15:58 UTC, adambkaplan commented
PR is currently missing a change to apply the transformer.

2024-07-24 12:30 UTC, sayan-biswas commented
These changes are incorporated in #50, hence closing this.

2024-07-24 12:30 UTC, closed without merging